[package]
name = "test_pass"
version = "0.1.0"
edition = "2024"
publish = false

[dependencies]
bevy = { git = "https://github.com/shengyusi-SYS/bevy.git", branch = "sys/bevy-0.19-lianyin", version = "0.19.0", default-features = false, features = [
    "bevy_ui",
    "bevy_text",
] }
bevy_tailwind_macro = { path = "../../" }
bevy_tailwind = { path = "../../../" }
